Repository GDSC-CAU/Vridge-Android, pull requests merged in 2024-02, with the labels that each got.

#26 [DEV] Android Model Class 생성
  app/src/main/java/com/gdsc_cau/vridge/models/Gender.kt
  app/src/main/java/com/gdsc_cau/vridge/models/User.kt
  app/src/main/java/com/gdsc_cau/vridge/models/Voice.kt
Labels: dev

#28 [DEV] Android Profile UI 구성
  app/src/main/java/com/gdsc_cau/vridge/profile/ProfileScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/utils/FirebaseAuthUtil.kt
  app/src/main/res/values/strings.xml
Labels: dev

#33 [FIX] Android VoiceList UI 테스트용 버튼 추가
  app/src/main/java/com/gdsc_cau/vridge/main/MainScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/voicelist/VoiceListScreen.kt
Labels: fix

#36 [DEV] Android RecordUI 구성
  app/src/main/java/com/gdsc_cau/vridge/record/RecordScreen.kt
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/drawable/ic_recording.xml
  app/src/main/res/values/strings.xml
Labels: dev

#35 [DEV] Android Talk UI 구성
  app/src/main/java/com/gdsc_cau/vridge/main/MainBottomBar.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/talk/TalkScreen.kt
  app/src/main/res/drawable/ic_downloading.xml
  app/src/main/res/drawable/ic_play_arrow.xml
  app/src/main/res/drawable/ic_play_stop.xml
  app/src/main/res/drawable/ic_send.xml
Labels: dev

#39 [DEV / FIX] Android Recording UI 애니메이션 적용 및 Profile UI 업데이트
  app/build.gradle.kts
  app/src/main/java/com/gdsc_cau/vridge/ui/profile/ProfileScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordScreen.kt
  app/src/main/res/raw/anim_lottie_loading.json
Labels: fix, dev

#40 [DEV] Voice List 화면 구현
  app/src/main/java/com/gdsc_cau/vridge/ui/main/MainScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListViewModel.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/values/strings.xml
Labels: dev

#42 [DEV] Android 앱 아이콘 적용
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: dev

#45 [DEV] Login ViewModel 로직 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdsc_cau/vridge/data/di/ApiModule.kt
  app/src/main/java/com/gdsc_cau/vridge/data/di/FirebaseModule.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/UserRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/login/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/login/LoginViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/utils/FirebaseAuthUtil.kt
Labels: dev

#46 [DEV] Profile ViewModel 연결
  .editorconfig
  app/src/main/java/com/gdsc_cau/vridge/data/database/FileStorage.kt
  app/src/main/java/com/gdsc_cau/vridge/data/di/FirebaseModule.kt
  app/src/main/java/com/gdsc_cau/vridge/data/models/User.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/profile/ProfileScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/profile/ProfileViewModel.kt
Labels: dev

#50 [DEV] Recording ViewModel 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdsc_cau/vridge/data/database/FileStorage.kt
  app/src/main/java/com/gdsc_cau/vridge/data/di/ApiModule.kt
  app/src/main/java/com/gdsc_cau/vridge/data/di/FirebaseModule.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/main/MainActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/main/MainScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListScreen.kt
  app/src/main/res/values/strings.xml
Labels: dev

#51 [DEV] VoiceList 화면 ViewModel 연결
  app/src/main/java/com/gdsc_cau/vridge/data/models/Voice.kt
  app/src/main/java/com/gdsc_cau/vridge/data/models/VoiceListDto.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListViewModel.kt
Labels: dev

#53 [FIX] 로그인이 유지되지 않는 오류
  app/src/main/java/com/gdsc_cau/vridge/ui/login/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/login/LoginViewModel.kt
Labels: fix

#54 [DEV] Talk 뷰모델 로직 연결
  app/src/main/java/com/gdsc_cau/vridge/data/database/FileStorage.kt
  app/src/main/java/com/gdsc_cau/vridge/data/database/InfoDatabase.kt
  app/src/main/java/com/gdsc_cau/vridge/data/models/Tts.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/TalkRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/TalkRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/talk/TalkScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/talk/TalkViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListScreen.kt
Labels: dev

#56 [DEV] Android Login UI 아이콘 변경
  app/src/main/java/com/gdsc_cau/vridge/ui/login/LoginScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Color.kt
  app/src/main/res/drawable/ic_vridge.png
Labels: dev

#57 [FIX] Backend 연동 및 dummy data 삭제
  app/src/main/assets/script.txt
  app/src/main/java/com/gdsc_cau/vridge/data/api/VridgeApi.kt
  app/src/main/java/com/gdsc_cau/vridge/data/database/InfoDatabase.kt
  app/src/main/java/com/gdsc_cau/vridge/data/models/ApiResponse.kt
  app/src/main/java/com/gdsc_cau/vridge/data/models/VoiceListDto.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/TalkRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/TalkRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/talk/TalkScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/talk/TalkViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/voicelist/VoiceListScreen.kt
Labels: fix

#58 [DOC] README 추가
  README.md
Labels: doc

#60 [DOC] Android README 수정
  README.md
Labels: doc

#61 [FIX] Recording 오류 수정
  app/src/main/assets/script.txt
  app/src/main/java/com/gdsc_cau/vridge/data/database/FileStorage.kt
  app/src/main/java/com/gdsc_cau/vridge/data/database/InfoDatabase.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepository.kt
  app/src/main/java/com/gdsc_cau/vridge/data/repository/VoiceRepositoryImpl.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/RecordViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/record/VoiceSettingDialog.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/util/LoadingDialog.kt
Labels: fix

#62 [DOC] Android README 최종
  README.md
Labels: doc

#63 [DOC] Android MIT License 적용
  LICENSE
Labels: doc
