Repository GDSC-CAU/Vridge-Android, pull requests merged in 2024-01, with the labels that each got.

#2 [DOC] Android Project 컨벤션
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  Convention.md
Labels: doc

#6 [DEV] Compose Theme 색상 정의
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Color.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Theme.kt
Labels: dev

#8 [DEV] 외부 라이브러리 추가
  app/build.gradle.kts
  app/src/main/java/com/gdsc_cau/vridge/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/MainActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/VridgeApp.kt
  build.gradle.kts
Labels: dev

#10 [DEV] PR 자동 convention check 액션 추가
  .github/workflows/ktlint-check.yml
Labels: dev

#11 [DEV] Manifest 어플리케이션 이름 변경
  app/src/main/AndroidManifest.xml
Labels: dev

#17 [FIX] KtLint 관련 수정
  .editorconfig
  .github/workflows/ktlint-check.yml
  app/build.gradle.kts
  app/src/androidTest/java/com/gdsc_cau/vridge/ExampleInstrumentedTest.kt
  app/src/main/java/com/gdsc_cau/vridge/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/MainActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/VridgeApp.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Color.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Theme.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Type.kt
  app/src/test/java/com/gdsc_cau/vridge/ExampleUnitTest.kt
Labels: fix

#15 [DEV] Android Login UI 구성 및 Firebase Auth 연동
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdsc_cau/vridge/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/login/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/login/LoginScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/login/LoginViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/utils/FirebaseAuthUtil.kt
  app/src/main/res/drawable/btn_signin_google.png
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: dev

#19 [DEV] Main Activity 기본 설정
  .editorconfig
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdsc_cau/vridge/login/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainBottomBar.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainNavigator.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainTab.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainTopBar.kt
  app/src/main/java/com/gdsc_cau/vridge/main/MainViewModel.kt
  app/src/main/java/com/gdsc_cau/vridge/profile/ProfileNavigation.kt
  app/src/main/java/com/gdsc_cau/vridge/profile/ProfileScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/record/RecordNavigation.kt
  app/src/main/java/com/gdsc_cau/vridge/record/RecordScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/talk/TalkNavigation.kt
  app/src/main/java/com/gdsc_cau/vridge/talk/TalkScreen.kt
  app/src/main/java/com/gdsc_cau/vridge/ui/theme/Color.kt
  app/src/main/java/com/gdsc_cau/vridge/voicelist/VoiceListNavigation.kt
  app/src/main/java/com/gdsc_cau/vridge/voicelist/VoiceListScreen.kt
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_voice.xml
Labels: dev

#21 [DEV] 로그인 관련 데이터 로직 Migration
  app/build.gradle.kts
  app/src/main/java/com/gdsc_cau/vridge/login/LoginActivity.kt
  app/src/main/java/com/gdsc_cau/vridge/login/LoginViewModel.kt
Labels: dev

#23 [DEV] Android Firebase Crashlytics 구성
  app/build.gradle.kts
  app/src/main/java/com/gdsc_cau/vridge/login/LoginViewModel.kt
  build.gradle.kts
Labels: dev
